# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aae4d025aab079cdf71b0d15f1b01062ad7af5a9c76585425135afa24fed7a0cc0bd16977dacf7b92b1e77e386c2072a98cdc73063cf6de30bff2c12162c8686

test:
  secret_key_base: cb7c49711fadab5156f2e9d6bfa87234f07e872c54c63040af97d8e927492da6488aaf32886ce32bc13e878a2a7bb9b5abf8aab3dafcf3c282d8a8eb342c5c0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
